### PR TITLE
routes to review

### PR DESCRIPTION
**Pull request by Za-hell**
The TA pointed out the routes was not well reviewed. They advise to recheck. 
> Need to redo the line 14. It conflicts with line 7 (Joao opinion) Sheets User Stories
> Line 19 and 13 conflict. Sheets User Stories
> Joao suggest a dashboard for favorite recipes in /pages_controller/dashboard/def_dash
> Line 26. Sheets User Stories -should we change the action to destroy ?
> The paths should always be plural.
> Line 8 is done by devise. 

Happy to keep working in the routes tomorrow if not done.

### CODE REVIEW

**Review by syboulette — COMMENTED** [review]
Is this complete?

**Comment by syboulette** [comment]
Also, please have it checked by Dom or Ariane first. We discussed that a few times already :)

**Comment by Za-hell** [comment]
> 

Depends! Do you mind to connect to GT so we can go over the user stories again?

**Review by D-Zaleski — APPROVED** [review]
lgtm. As Ines said yesterday evening, These routes may be subject to change. If we do one feature at a time e.g. fridge, we should be good.

**Review by syboulette — APPROVED** [review]

**Pull request merged**
