### PR TITLE
display fridge is working

### PR DESCRIPTION
**Pull request by Za-hell**
I've removed the index.
Fix the show fridge to the path my-fridgy
View page is working.

### CODE REVIEW

**Comment by Za-hell** [comment]
Screenshot from 2023-03-10 22-24-59

Question, will the form be the way to add ingredient in the fridge? I mean the fridge will be empty and besides the ingredient name in the circle button, we click it - and it is an option to add ingredients? Or should we add a button to add ingredients?

fridgii

**Comment by syboulette** [comment]
@Za-hell Everything that is circled in orange are potential feature that we will devellop after we are done with the basic ones. So don't worry about the freshness indicators :)
Yes, we definitely need a add ingredient to fridge button :)

**Comment by Za-hell** [comment]
> 

Thank you, that was very helpful

**Review by akramerin — APPROVED** [review]
lgtm

**Review by D-Zaleski — APPROVED** [review]

**Pull request merged**
